### ISSUE TITLE
Xcode10报错libstdc++.6.0.9.tbd

### ISSUE THREAD

**Issue by SarahWuOnePencil** [BaiduLBS/BaiduMapKit#43]
Xcode 10升级之后，项目当中使用的百度地图是使用libstdc++.6.0.9.tbd，导致每一次更新Xcode都要重新解决工具当中已经移除libstdc++.6.0.9.tbd所出现的问题，那么请问SDK什么时候会更新解决这个问题呢？

**Comment by harveyseeking** [comment]
新版本已经解决了这个问题
