### ISSUE TITLE
步骑行导航可以直接使用BaiduMapAPI_Map组件吗

### ISSUE THREAD

**Issue by Rxx9723** [BaiduLBS/BaiduMapKit#49]
官方文档指出：步骑行导航地图功能包为BaiduMapAPI_Map_For_WalkNavi.framework，BaiduMapAPI_Map_For_WalkNavi组件包含了BaiduMapAPI_Map组件的所有功能。
那么：是否意味着，1、直接pod  BaiduMapKit  后，2、手动添加 BaiduMapAPI_WalkNavi.framework 步骑行导航即可使用

**Comment by BaiduLBS** [comment]
您上述1，2操作后会出现符号重复错误，建议您手动集成。

BaiduMapAPI_Base.framework
BaiduMapAPI_Map_For_WalkNavi.framework
BaiduMapAPI_WalkNavi.framework
