### ISSUE TITLE
import文件时文件名大小写不对

### ISSUE THREAD

**Issue by AiweiChujian** [BaiduLBS/BaiduMapKit#51]
**BMKSearchComponent.h**这个文件中
```
#import "BMKPOISearchResult.h"
#import "BMKGeoCodeSearchOption.h"
```
上面两行引入，文件名的大小写有误，在编译时只是一个编译警告，但在使用中却会导致injectionIII这款工具无法使用（ “could not find file” ），希望能在后续版本中修复这儿的问题

**Comment by BaiduLBS** [comment]
好的，下个版本会修复下
