### ISSUE TITLE
5.3.0 运行提示报错  Showing Recent Messages Undefined symbol: ___darwin_check_fd_set_overflow

### ISSUE THREAD

**Issue by a603938361** [BaiduLBS/BaiduMapKit#52]
5.2.0 正常运行

max os 10.15.3
xcode 11.3.1

Undefined symbols for architecture x86_64:
  "___darwin_check_fd_set_overflow", referenced from:
      _baidu_vi::CVSocketMan::SocketThreadProc(void*) in BaiduMapAPI_Base(VSocket.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by q819438477** [comment]
我也是这问题：是不是缺少某依赖库
现在指定版本5.2.0了

**Comment by BJBJBJ** [comment]
> 5.2.0 正常运行
> 
> max os 10.15.3
> xcode 11.3.1
> 
> Undefined symbols for architecture x86_64:
> "___darwin_check_fd_set_overflow", referenced from:
> _baidu_vi::CVSocketMan::SocketThreadProc(void*) in BaiduMapAPI_Base(VSocket.o)
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)


您好，xcode升级至11.4即可。

**Comment by BJBJBJ** [comment]
> 我也是这问题：是不是缺少某依赖库
> 现在指定版本5.2.0了

您好，xcode升级至11.4即可。

**Comment by a603938361** [comment]
ok ths
